sudo: required
services:
  - docker

before_install:
  - docker build -t smithprince22/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true smithprince22/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-332499208368"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
